name: hello-world
on: push
jobs:
  Clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    needs: Clone
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Run tests
        run: | 
          chmod +x ./ci/unit-test-app.sh
          ./ci/unit-test-app.sh
  Build:
    needs: Clone
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Build app
        run: |
          chmod +x ./ci/build-app.sh
          ./ci/build-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: 
      - Build
      - Test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: build docker
        run: |
          chmod +x ci/build-docker.sh
          export GIT_COMMIT="GA-$GITHUB_SHA"
          ci/build-docker.sh
      - name: push docker
        run: | 
          chmod +x ci/push-docker.sh
          export GIT_COMMIT="GA-$secrets.GITHUB_SHA"
          ci/push-docker.sh --username ${{ secrets.DOCKER_USERNAME }} --pasword ${{ secrets.DOCKER_PASSWORD }}
  build-and-push-latest-actions:
    runs-on: ubuntu-latest
    needs: 
      - Build
      - Test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Show dirs
        run: ls -a -R
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: my-org/my-image:latest