name: hello-world
on: push

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  
jobs:
  Clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    needs: Clone
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Run tests
        run: | 
          chmod +x ./ci/unit-test-app.sh
          ./ci/unit-test-app.sh
  Build:
    needs: Clone
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Build app
        run: |
          chmod +x ./ci/build-app.sh
          ./ci/build-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: 
      - Build
      - Test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: build docker
        run: |
          export GIT_COMMIT="GA-$GITHUB_SHA" &&
          chmod +x ci/build-docker.sh &&
          ci/build-docker.sh
      - name: push docker
        run: | 
          export GIT_COMMIT="GA-$GITHUB_SHA" &&
          chmod +x ci/push-docker.sh &&
          ci/push-docker.sh 
  Component-test:
    needs: 
      - Docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Run test
        run: |
          export GIT_COMMIT="GA-$GITHUB_SHA" &&
          chmod +x ci/component-test.sh 
          ci/component-test.sh