name: hello-world
on: push
jobs:
  "Clone repo":
    runs-on: ubuntu-latest
  Test:
    needs: "Clone repo"
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: | 
          ./ci/unit-test-app.sh
  Build:
    needs: "Clone repo"
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Build app
        run: | 
          ./ci/build-app.sh
  Deploy:
    needs: 
      - Test
      - Build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .


          
