name: hello-world
on: push
jobs:
  test-app:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: | 
          ./ci/unit-test-app.sh
  build-app:
    needs: test-app
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Build app
        run: | 
          ./ci/build-app.sh
  deploy-app:
    needs: build-app
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .


          
